services:
  - type: web
    name: ai-resume-builder
    env: python
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y libpango-1.0-0 libcairo2 libgdk-pixbuf-2.0-0 libffi-dev
      pip install -r requirements.txt
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
